### ISSUE TITLE
outlying photometry checker

### ISSUE THREAD

**Issue by jrob93** [lsst-uk/adler#106]
Write a function to test the compatibility of new photometry with an exisiting phase curve model.

---

This is related to item 1 in the FY24 Q2 (Mar'23) QU plan for April to June 2024, ie. 

> 1) Model Magnitude Difference functions , check flags functions,
     and color analysis functions will be implemented in the next quarter.

**Comment by tms-epcc** [comment]
@jrob93 is this part of #97?

**Comment by jrob93** [comment]
Yes it is, I presume it can be associated with the "Epic"?

**Comment by tms-epcc** [comment]
> Yes it is, I presume it can be associated with the "Epic"?

Thanks @jrob93, you'll see that I have now done that.
