### ISSUE TITLE
User view presentation

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/adler#13]
From [20/SEP/23 Lasair-Adler meeting](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3272736771/20+SEP+23+Adler+-+Lasair)

**Comment by tms-epcc** [comment]
18/OCT/23
- presentation given at [18/OCT/23 Adler-Lasair meeting](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3288596481/18+OCT+23+Adler+-+Lasair)
- Waiting for slides

**Comment by mschwamb** [comment]
Slides posted
