### ISSUE TITLE
Define Phase C SRD requirements

### ISSUE THREAD

**Issue by mschwamb** [lsst-uk/adler#21]

**Comment by tms-epcc** [comment]
30/JAN/23
- Stephen in Project Scientist reviewed all the update to the [LSST:UK SRD](https://lsst-uk.atlassian.net/wiki/spaces/LUSCSWG/pages/614465537)
- The updated SRD is due for submission by 31/JAN/24 but Stephen wants to wait until the Lasair /Adler integration is agreed and so the Adler SRD reqs can be updated if necessary

**Comment by tms-epcc** [comment]
Considered at 26/MAR/26 six month review meeting.  Agreed to wait until Lasair integration becomes clearer before making any updates.
