### ISSUE TITLE
Create data for testing

### ISSUE THREAD

**Issue by astronomerritt** [lsst-uk/adler#31]
Testing the classes I wrote to store data is impossible off the RSP at the moment, which is problematic. 

The most elegant way to do this will be to create a small SQL database with exactly the same tables as the RSP for a single object using DP0.3 data. There's already some placeholder code in the classes where I can add functionality to read from a SQL database.

**Comment by astronomerritt** [comment]
I think *.db is in the .gitignore  so I'll probably have to remove that.

**Comment by jrob93** [comment]
This would be awesome for working on a local machine. It would be ideal if we could have a small number of objects representing the main dynamical groups (e.g. main belt asteroids, near earth objects, transneptunian objects)
