### ISSUE TITLE
Suppress or otherwise investigate UserWarning when reading in

### ISSUE THREAD

**Issue by astronomerritt** [lsst-uk/adler#34]
When converting columns from the AstroPy tables RSP uses for data to Numpy arrays, if the column contains a masked element the following warning appears:

```UserWarning: Warning: converting a masked element to nan.```

This may well be desired behaviour but I don't want to just suppress the warning: I'd like to know 

- what's being masked and why
- whether there's a more elegant way of handling it (Numpy masked arrays?)

**Comment by mschwamb** [comment]
Best place to ask about this is https://community.lsst.org/

**Comment by astronomerritt** [comment]
Investigated more so I'm asking the right questions.

This is because the `n` column in the MPCORB catalog on DP0.3 (mean daily motion in degrees per day) is masked: at least, the first fifty entries are. I assume this means they're unpopulated. When converting to numpy arrays from the Astropy table, these become NaNs.

So the question is in fact "why isn't n populated in the MPCORB catalog of DP0.3?".
