### ISSUE TITLE
Obtain approval for in-kind workplan

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/adler#5]

**Comment by tms-epcc** [comment]
30/JUN/23
- request sent Meg and Colin to update the LSST:UK In-kind proposal with Adler content by 31/JUL/23
- once this is complete then the inkind workplan can be tackled

**Comment by tms-epcc** [comment]
30/AUG/23
- following instructions from KnutO, asked Colin and Meg to go ahead and start to fill in the form at https://ls.st/ikc-wp  but NOT to hit the submit button for it just yet.  KnutO will say when that can be done.

**Comment by mschwamb** [comment]
Given go ahead to fill in the form. We will submit sometime in January. Currently the SSSC is reviewing our plans based on the fedeback from the Adler+Lasair calls.

**Comment by tms-epcc** [comment]
30/JAN/23
@mschwamb reported 
- aiming to get workplan submitted to Inkind system by end of February. 
- waiting for SSSC Software Group to finally sign off the plan before submission to IPC

**Comment by tms-epcc** [comment]
Aprajita at 01/MAR/24 Team meeting explained that IPC feedback will only be provided when necessary and hence this should be considered closed until informed by IPC team if further updates needed
